### ISSUE TITLE
Folders and project.pbxproj file not updated with git

### ISSUE THREAD

**Issue by Hassan1Hr** [mosliem/podCapsule#1]
You should check your working project with git as it not updated correctly, as example:

- Podfile not contains 'NVActivityIndicatorView' & 'lottie-ios'.
- project.pbxproj file not synchronized with the project folders.

**Comment by mosliem** [comment]
Hi Hassan 
Thanks for your effort.
- I fixed the issue of the **project.pbxproj**
- Updated the readme file to avoid the SKCountryPicker Pod error.

if you find any errors, don't hesitate to mention them.
